# Generated by Django 5.2.1 on 2025-06-24 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0006_cliente_criado_por_motorista_criado_por_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='app_controller_usuario_set', related_query_name='app_controller_usuario', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Formato: (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='app_controller_usuario_set', related_query_name='app_controller_usuario', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterConstraint(
            model_name='usuario',
            name='unique_username',
            constraint=models.UniqueConstraint(fields=('username',), name='unique_username'),
        ),
        migrations.AlterConstraint(
            model_name='usuario',
            name='unique_email',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
    ]
